#include <stdafx.hpp>
#include <render/menu/localization.hpp>

namespace render::localization {

	namespace {

		std::atomic<id> g_current{ id::en };

		const std::unordered_map<std::string_view, const char*>& russian( )
		{
			static const std::unordered_map<std::string_view, const char*> table{

				{ "Aimbot", "Аим" },
				{ "Triggerbot", "Триггер" },
				{ "Visuals", "Визуалы" },
				{ "Misc", "Разное" },

				{ "Global", "Общие" },
				{ "Pistol", "Пистолеты" },
				{ "SMG", "ПП" },
				{ "Rifle", "Винтовки" },
				{ "Shotgun", "Дробовики" },
				{ "Sniper", "Снайперки" },
				{ "Heavy", "Пулемёты" },

				{ "TARGETING", "НАВЕДЕНИЕ" },
				{ "PENETRATION", "ПРОБИТИЕ" },
				{ "VISUALIZATION", "ОТОБРАЖЕНИЕ" },
				{ "TRIGGERBOT CORE", "ТРИГГЕР" },
				{ "ADVANCED MODE", "РАСШИРЕННЫЙ" },

				{ "MOVEMENT", "АВТОСТОП" },
				{ "OVERRIDE SETTINGS", "ПЕРЕОПРЕДЕЛЕНИЕ" },

				{ "Master Switch", "Включить" },
				{ "Activation", "Активация" },
				{ "Activation Mode", "Режим активации" },
				{ "Hold", "По удержанию" },
				{ "Always On", "Всегда" },
				{ "Toggle", "Переключение" },
				{ "Damage Override", "Переопределение урона" },
				{ "Override Damage", "Альтернативный урон" },
				{ "Checks", "Условия" },
				{ "Jump", "Прыжок" },
				{ "Flash", "Ослепление" },
				{ "Airborne", "В воздухе" },
				{ "Flashed", "Ослепление" },
				{ "Threshold", "Порог" },
				{ "Smoke", "Дым" },
				{ "Walls", "Стены" },
				{ "Block", "Запрет" },
				{ "Penetration", "Пробитие" },
				{ "Ignore", "Игнорировать" },
				{ "Trigger Key", "Бинд" },
				{ "FOV", "FOV" },
				{ "FOV Profile", "Профиль FOV" },
				{ "Radius", "Радиус" },
				{ "Max Radius", "Макс. радиус" },
				{ "Min Radius", "Мин. радиус" },
				{ "Full Size At", "Полный размер до" },
				{ "Min Size At", "Мин. размер после" },
				{ "Advanced", "Дополнительно" },
				{ "Fixed", "Фиксированный" },
				{ "Distance", "По дистанции" },
				{ "Target", "На цели" },
				{ "Near Distance", "Ближняя дистанция" },
				{ "Near FOV", "Ближний FOV" },
				{ "Far Distance", "Дальняя дистанция" },
				{ "Far FOV", "Дальний FOV" },
				{ "Acquisition Area", "Область захвата" },
				{ "Target Point", "Точка наведения" },
				{ "Show FOV", "Показывать FOV" },
				{ "Visualization", "Визуализация" },
				{ "Smoothing", "Сглаживание" },
				{ "Humanize", "Хуманизация" },
				{ "Humanizer Tuning", "Тонкая настройка" },
				{ "Humanizer Profile", "Профиль хуманизации" },
				{ "Motion", "Движение" },
				{ "Behavior", "Поведение" },
				{ "Gravity", "Притяжение" },
				{ "Wind", "Отклонение" },
				{ "Max Step", "Максимальный шаг" },
				{ "Damping", "Затухание" },
				{ "Reaction Min", "Мин. реакция" },
				{ "Reaction Max", "Макс. реакция" },
				{ "Curve", "Кривизна" },
				{ "Overshoot Chance", "Шанс перелёта" },
				{ "Overshoot Amount", "Сила перелёта" },
				{ "Jitter", "Микродрожание" },
				{ "Deadzone", "Мёртвая зона" },
				{ "Hitboxes", "Хитбоксы" },
				{ "Multi-Point", "Мультипоинт" },
				{ "Cap Points", "Торцевые точки" },
				{ "Side Points", "Боковые точки" },
				{ "Head Scale", "Масштаб головы" },
				{ "Body Scale", "Масштаб тела" },
				{ "Limbs Scale", "Масштаб конечностей" },
				{ "Prediction", "Предикт" },
				{ "Max Horizon", "Горизонт предикта" },
				{ "Acceleration", "Учитывать ускорение" },
				{ "RCS", "Контроль отдачи" },
				{ "Start Bullet", "Начальная пуля" },
				{ "Pitch Strength", "Сила по вертикали" },
				{ "Yaw Strength", "Сила по горизонтали" },
				{ "Humanization", "Хуманизация" },
				{ "Response", "Отклик" },
				{ "Gain Randomness", "Разброс силы" },
				{ "Drift", "Дрейф" },
				{ "Correction Time", "Время коррекции" },
				{ "Smoothness", "Плавность" },
				{ "Strength Variation", "Вариация силы" },
				{ "Path Drift", "Дрейф траектории" },
				{ "Wall Policy", "Прострелы" },
				{ "Only Visible", "Только видимые" },
				{ "Shot Timing", "Тайминг выстрела" },
				{ "Randomize", "Рандомизация" },
				{ "Outlier Chance", "Шанс выброса" },
				{ "Outlier Delay", "Задержка выброса" },
				{ "Lethal Only", "Только смертельный урон" },
				{ "R8 Readiness", "Готовность R8" },
				{ "Release Margin", "Запас отпускания" },
				{ "Key", "Бинд" },
				{ "Visible Only", "Только по видимым" },
				{ "Predictive", "Предикт" },
				{ "Recoil Sync", "Контроль отдачи" },
				{ "Auto Wall", "Autowall" },
				{ "Min Damage", "Мин. урон" },
				{ "Draw FOV Circle", "Рисовать FOV" },
				{ "Mode", "Режим" },
				{ "Interface Colors", "Цвета интерфейса" },
				{ "Typography", "Текст" },
				{ "Primary Text", "Основной текст" },
				{ "Muted Text", "Вторичный текст" },
				{ "Surfaces", "Поверхности" },
				{ "Menu Background", "Фон меню" },
				{ "Controls", "Элементы управления" },
				{ "Containers", "Контейнеры" },
				{ "Popups", "Всплывающие окна" },
				{ "Interaction", "Взаимодействие" },
				{ "Accent", "Акцент" },
				{ "Hover", "Наведение" },
				{ "Borders", "Границы" },
				{ "Seed Type", "Сид" },
				{ "Hitchance", "Шанс попасть" },
				{ "Delay (ms)", "Задержка (мс)" },
				{ "Reaction Time (ms)", "Время реакции (мс)" },
				{ "Auto Stop", "Auto Stop" },
				{ "Early Auto Stop", "Early Auto Stop" },
				{ "Delay Before", "Задержка до" },
				{ "Delay After", "Задержка после" },
				{ "Randomize (+-)", "Рандом (±)" },
				{ "Inherit Global Settings", "Как в общих" },

				{ "Advanced", "Расширенный" },
				{ "None", "Нет" },
				{ "All", "Все" },
				{ "Restricted", "Ограниченный" },
				{ "Unrestricted", "Свободный" },
				{ "Head", "Голова" },
				{ "Body", "Тело" },
				{ "Arms", "Руки" },
				{ "Legs", "Ноги" },

				{ "Players", "Игроки" },
				{ "Items", "Дроп" },
				{ "Projectiles", "Гранаты" },
				{ "Bomb", "Бомба" },
				{ "Radar", "Радар" },
				{ "World", "Мир" },
				{ "Crosshair", "Прицел" },

				{ "Player Names", "Имена игроков" },
				{ "Player Health", "Здоровье игроков" },
				{ "Player Armor", "Броня игроков" },
				{ "Player Weapon", "Оружие игроков" },
				{ "Grenade Markers", "Маркеры гранат" },
				{ "Grenade Trajectories", "Траектории гранат" },
				{ "Grenade Zones", "Зоны гранат" },
				{ "Information Scale", "Масштаб информации" },
				{ "Overlay Enemy Markers", "Маркеры противников" },
				{ "Enemy Marker", "Маркер противника" },
				{ "View Direction", "Направление взгляда" },
				{ "Status Text", "Текст состояния" },
				{ "Marker Scale", "Масштаб маркера" },
				{ "Text Outline", "Обводка текста" },
				{ "HE Color", "Цвет HE" },
				{ "Flash Color", "Цвет световой" },
				{ "Smoke Color", "Цвет дыма" },
				{ "Molotov Color", "Цвет огня" },
				{ "Decoy Color", "Цвет ложной" },
				{ "Line Thickness", "Толщина линии" },
				{ "End Point Size", "Размер конечной точки" },
				{ "Fill Opacity", "Прозрачность заливки" },
				{ "Outline Opacity", "Прозрачность контура" },
				{ "In-Game Avatars", "Внутриигровые аватары" },
				{ "Copy Game Crosshair", "Копировать игровой прицел" },
				{ "Outline Color", "Цвет обводки" },
				{ "Outline Thickness", "Толщина обводки" },

				{ "MASTER", "ОСНОВНОЕ" },
				{ "BOUNDING BOX", "БОКС" },
				{ "DETAILS", "ИНФА" },
				{ "SKELETON & HITBOXES", "СКЕЛЕТ И ХИТБОКСЫ" },
				{ "Enable Player ESP", "Включить ESP" },
				{ "Legit Sync", "Легитная синхронизация" },
				{ "Spectator Sync", "Синхронизация со зрителями" },
				{ "Direct Visibility", "Прямая видимость" },
				{ "Radar Spotted", "Обнаружение радаром" },
				{ "Audible Sounds", "Слышимые звуки" },
				{ "Radar Hold", "Время радара" },
				{ "Sound Hold", "Время звука" },
				{ "Hearing Distance", "Дистанция слышимости" },
				{ "Pulse Minimum", "Минимум пульсации" },
				{ "Pulse Maximum", "Максимум пульсации" },
				{ "Pulse Period", "Период пульсации" },
				{ "Show Box", "Бокс" },
				{ "Style", "Стиль" },
				{ "Full", "Полный" },
				{ "Cornered", "Углы" },
				{ "Corner Length", "Длина углов" },
				{ "Background Fill", "Заливка" },
				{ "Box Visible Color", "Бокс: видимые" },
				{ "Box Occluded Color", "Бокс: за стеной" },
				{ "Fill Visible Color", "Заливка: видимые" },
				{ "Fill Occluded Color", "Заливка: за стеной" },
				{ "Show Name", "Ник" },
				{ "Show Weapon", "Оружие" },
				{ "Ammo Indicator", "Индикатор патронов" },
				{ "Exact Ammo Count", "Точное число патронов" },
				{ "Empty Color", "Цвет пустой части" },
				{ "Bomb Damage", "Урон от бомбы" },
				{ "Health Bar", "Бар ХП" },
				{ "Ammo Bar", "Бар патронов" },
				{ "Info Flags", "Флаги" },
				{ "Chams", "Чамсы" },
				{ "Antialiasing", "Сглаживание" },
				{ "Model Glow", "Свечение модели" },
				{ "Glow Color", "Цвет свечения" },
				{ "Glow Radius", "Радиус свечения" },
				{ "Glow Strength", "Яркость свечения" },
				{ "Glow Layers", "Слои свечения" },
				{ "Death Shatter", "Распад при смерти" },
				{ "On Hit Chams", "Чамсы при попадании" },
				{ "Kill Particles", "Частицы смерти" },
				{ "Particle Color", "Цвет частиц" },
				{ "Particle Duration", "Время частиц" },
				{ "Particle Size", "Размер частиц" },
				{ "Particle Count", "Количество частиц" },
				{ "On Shot Chams", "Чамсы при выстреле" },
				{ "Ghost Duration", "Время слепка" },
				{ "Ghost Appearance", "Вид слепка" },
				{ "Occlusion", "Перекрытия" },
				{ "Dynamic Doors", "Динамические двери" },
				{ "Smoke Occlusion", "Перекрытие дымом" },
				{ "Chams Visible", "Чамсы: видимые" },
				{ "Chams Occluded", "Чамсы: за стеной" },
				{ "Show Skeleton", "Скелет" },
				{ "Show Head Circle", "Круг на голове" },
				{ "Show View Line", "Линия взгляда" },
				{ "Offscreen Arrows", "Стрелки за экраном" },
				{ "Arrow Color", "Цвет стрелки" },
				{ "Arrow Size", "Размер стрелки" },
				{ "Arrow Radius", "Радиус стрелок" },
				{ "Bloom Speed", "Скорость свечения" },
				{ "Minimum Glow", "Минимальное свечение" },
				{ "Maximum Glow", "Максимальное свечение" },
				{ "Threat Hitboxes", "Хитбоксы" },
				{ "SOUND ESP", "ЗВУКИ" },
				{ "Sound ESP", "Звуки" },
				{ "Enable Sound ESP", "Показывать звуки" },
				{ "Ring Color", "Цвет круга" },
				{ "Local Sync", "Только слышимые" },
				{ "Duration", "Длительность" },
				{ "Ring Radius", "Радиус круга" },
				{ "Audible Distance", "Дальность слуха" },
				{ "Head Hitbox Color", "Цвет: голова" },
				{ "Body Hitbox Color", "Цвет: тело" },
				{ "Fill Alpha", "Прозрачность" },

				{ "Material", "Материал" },
				{ "Color", "Цвет" },
				{ "Wireframe", "Сетка" },
				{ "Roughness", "Шероховатость" },
				{ "Metalness", "Металличность" },
				{ "Exponent", "Степень" },
				{ "Falloff", "Спад" },
				{ "Fresnel Filling", "Заливка Френеля" },
				{ "Strength", "Интенсивность" },
				{ "Speed", "Скорость" },
				{ "Tint", "Оттенок" },
				{ "Solid", "Сплошной" },
				{ "Shaded", "С затенением" },
				{ "Glow", "Свечение" },

				{ "Glow Outline", "Контур" },
				{ "Iridescent", "Перелив" },
				{ "Water Flow", "Вода" },
				{ "Glossy", "Глянец" },

				{ "SETTINGS", "НАСТРОЙКИ" },
				{ "FILTERS", "ФИЛЬТРЫ" },
				{ "Enable Item ESP", "Включить ESP дропа" },
				{ "Max Distance", "Дистанция" },
				{ "Show Icon", "Иконка" },
				{ "Show Item Name", "Название" },
				{ "Rifles", "Винтовки" },
				{ "SMGs", "ПП" },
				{ "Snipers", "Снайперки" },
				{ "Pistols", "Пистолеты" },
				{ "Grenades", "Гранаты" },
				{ "Utility", "Утилити" },

				{ "VISUAL ELEMENTS", "ЭЛЕМЕНТЫ" },
				{ "COLORS", "ЦВЕТА" },
				{ "Enable Projectiles", "Включить ESP гранат" },
				{ "Display Mode", "Режим отображения" },
				{ "Indicator", "Индикатор" },
				{ "Text Only", "Только текст" },
				{ "Show Text", "Показывать текст" },
				{ "Effect Timer", "Таймер эффекта" },
				{ "Effect Timer Ring", "Кольцо таймера" },
				{ "Inferno Bounds", "Границы молика" },
				{ "INDICATOR", "ИНДИКАТОР" },
				{ "Timer Full", "Таймер: полный" },
				{ "Timer Low", "Таймер: конец" },
				{ "Indicator Background", "Фон индикатора" },
				{ "INFERNO GRADIENT", "ГРАДИЕНТ INFERNO" },
				{ "Gradient Width", "Ширина градиента" },
				{ "Gradient Opacity", "Яркость градиента" },
				{ "HE Grenade", "Хешка" },
				{ "Flashbang", "Флешка" },
				{ "Smoke", "Смок" },
				{ "Molotov", "Молик" },
				{ "Decoy", "Декой" },

				{ "STATES", "СОСТОЯНИЯ" },
				{ "SAFE ZONE (BAKED)", "БЕЗОПАСНАЯ ЗОНА" },
				{ "Enable Bomb ESP", "Включить ESP бомбы" },
				{ "Show Carrier", "Носитель бомбы" },
				{ "Show Planted", "Установленная" },
				{ "Planted Color", "Цвет установленной" },
				{ "Defusing Color", "Цвет дефуза" },
				{ "Panel Background", "Фон панели" },
				{ "World Timer Ring", "Кольцо таймера в мире" },
				{ "World Timer", "Таймер в мире" },
				{ "Bomb Info Panel", "Панель информации о бомбе" },
				{ "Timer Color", "Цвет таймера" },
				{ "Safe Zone Contour", "Контур зоны" },
				{ "Zone Color", "Цвет зоны" },
				{ "Gradient Bands", "Изолинии" },
				{ "Band Step", "Шаг изолиний" },

				{ "RADAR OVERLAY", "РАДАР" },
				{ "Overlay Enemy Markers", "Метки врагов" },
				{ "NO FLASH (WIREFRAME)", "NO FLASH (СЕТКА)" },
				{ "Enable Visual No Flash", "Включить No Flash" },
				{ "Render Distance", "Дистанция" },
				{ "Dimming Overlay Color", "Цвет затемнения" },
				{ "Wireframe Color", "Цвет сетки" },
				{ "NO SMOKE (WIREFRAME)", "NO SMOKE (СЕТКА)" },
				{ "Enable Visual No Smoke", "Включить No Smoke" },
				{ "Smoke Wireframe Color", "Цвет сетки в дыму" },

				{ "CROSSHAIR SETTINGS", "ПРИЦЕЛ" },
				{ "Enable Crosshair", "Включить прицел" },
				{ "Weapon Sync", "Синхронизация" },
				{ "Draw Dot", "Точка" },
				{ "Draw Lines", "Линии" },
				{ "T-Style", "T-образный" },
				{ "Length", "Длина" },
				{ "Gap", "Зазор" },
				{ "Thickness", "Толщина" },
				{ "Draw Outline", "Обводка" },
				{ "Primary Color", "Цвет" },
				{ "Penetration Indicator", "Индикатор пенетрации" },
				{ "Can Penetrate", "Пробьёт" },
				{ "Cannot Penetrate", "Не пробьёт" },

				{ "General", "Общее" },
				{ "Movement", "Мувмент" },
				{ "Effects", "Эффекты" },
				{ "Overlay", "Оверлей" },
				{ "Lua API", "Lua API" },
				{ "Configs", "Конфиги" },
				{ "LUA RUNTIME", "LUA RUNTIME" },
				{ "SCRIPTS", "СКРИПТЫ" },
				{ "Enable Lua API", "Включить Lua API" },
				{ "Script Directory", "Директория скриптов" },
				{ "Open Folder", "Открыть папку" },
				{ "Load Lua Script", "Загрузить Lua-скрипт" },
				{ "Copy link", "Копировать ссылку" },
				{ "Copy Path", "Копировать путь" },
				{ "Discover Scripts", "Обновить список" },
				{ "Refresh", "Обновить" },
				{ "No Lua scripts found", "Lua-скрипты не найдены" },
				{ "Copy scripts into the Lua directory", "Скопируйте скрипты в директорию Lua" },
				{ "Autoload", "Автозагрузка" },
				{ "Hot Reload", "Горячая перезагрузка" },
				{ "Status", "Статус" },
				{ "Runtime", "Выполнение" },
				{ "Last Error", "Последняя ошибка" },
				{ "Reload Script", "Перезагрузить скрипт" },
				{ "Reload", "Перезагрузить" },

				{ "AUTOMATION", "АВТОМАТИЗАЦИЯ" },
				{ "Auto Accept Match", "Автопринятие матча" },
				{ "GRENADES", "ГРАНАТЫ" },
				{ "LINEUP HELPER", "ПОМОЩНИК РАСКИДОК" },
				{ "GRENADE ASSIST", "ДОВОДКА ГРАНАТ" },
				{ "TRAJECTORY", "ТРАЕКТОРИЯ" },
				{ "Lineup Helper", "Раскидки" },
				{ "Draw Distance", "Дистанция отрисовки" },
				{ "Marker Distance", "Дистанция маркера" },
				{ "Stand Radius", "Радиус точки" },
				{ "Release Radius", "Точность позиции" },
				{ "Height Tolerance", "Допуск по высоте" },
				{ "Show Throw Type", "Тип броска" },
				{ "Show Distance", "Дистанция" },
				{ "Plaque Background", "Фон плашки" },
				{ "Plaque Text", "Текст плашки" },
				{ "Plaque Accent", "Акцент плашки" },
				{ "Stand Marker", "Маркер точки" },
				{ "Stand Marker Active", "Маркер точки (актив.)" },
				{ "Aim Marker", "Маркер наведения" },
				{ "Lineup Aim Assist", "Доводка на раскидку" },
				{ "Aim Key", "Бинд доводки" },
				{ "Auto Release", "Автоматический бросок" },
				{ "Lock Threshold", "Порог захвата" },
				{ "Settle Time", "Стабилизация" },
				{ "Enemy Aim Assist", "Доводка гранаты по врагу" },
				{ "Activation Key", "Бинд" },
				{ "Target FOV", "FOV поиска" },
				{ "Trajectory Preview", "Траектория" },
				{ "Local Prediction Only", "Только свои гранаты" },
				{ "Line Style", "Стиль линии" },
				{ "Line Color", "Цвет линии" },
				{ "Line Thickness", "Толщина линии" },
				{ "Bloom", "Свечение" },
				{ "Bloom Color", "Цвет свечения" },
				{ "Bloom Radius", "Радиус свечения" },
				{ "Bounce Points", "Точки отскока" },
				{ "End Point", "Конечная точка" },
				{ "Point Color", "Цвет точки" },
				{ "Point Size", "Размер точки" },
				{ "ENGINE", "ДВИЖОК" },
				{ "FPS Limiter", "Лимит FPS" },
				{ "Maximum FPS", "Максимум FPS" },
				{ "INTERFACE", "ИНТЕРФЕЙС" },
				{ "LANGUAGE", "ЯЗЫК" },
				{ "Language", "Язык" },
				{ "DPI Scale", "Масштаб DPI" },

				{ "BUNNY HOP", "BUNNY HOP" },
				{ "EDGE JUMP", "EDGE JUMP" },
				{ "Enable Bunny Hop", "Включить Bunny Hop" },
				{ "Enable Edge Jump", "Включить Edge Jump" },

				{ "BULLET TRACERS", "ТРАССЕРЫ" },
				{ "Enable Bullet Tracers", "Включить трассеры" },
				{ "Tracer Color", "Цвет трассера" },
				{ "Fade Duration", "Время затухания" },
				{ "Max Tracers", "Макс. трассеров" },
				{ "Bloom Effect", "Bloom" },
				{ "Draw Impact Cubes", "Метки попаданий" },
				{ "Draw Trajectory Line", "Линия траектории" },
				{ "Cube Size", "Размер метки" },
				{ "Fade Near", "Затухание вблизи" },
				{ "Fade Far", "Затухание вдали" },

				{ "CAPTURE", "ЗАХВАТ ЭКРАНА" },
				{ "OBS Bypass", "Обход OBS" },
				{ "WATERMARK", "ВОТЕРМАРКА" },
				{ "Show Watermark", "Показывать" },
				{ "Show Ping", "Пинг" },
				{ "Show Loss", "Лосс" },
				{ "Show CPU Load", "Нагрузка CPU" },
				{ "Show FPS", "FPS" },

				{ "SPECTATOR LIST", "НАБЛЮДАТЕЛИ" },
				{ "Show Spectators", "Показывать" },
				{ "EVENT LOG", "ЖУРНАЛ СОБЫТИЙ" },
				{ "Event Log", "Журнал событий" },
				{ "Show Event Log", "Показывать журнал" },
				{ "Maximum Entries", "Количество записей" },
				{ "Events", "События" },
				{ "Shots", "Выстрелы" },
				{ "Hits", "Попадания" },
				{ "Kills", "Убийства" },
				{ "Misses", "Промахи" },
				{ "Blocked", "Блокировки" },
				{ "Info", "Информация" },
				{ "ACTIVE BINDS", "АКТИВНЫЕ БИНДЫ" },
				{ "Active Binds", "Активные бинды" },
				{ "Show Active Binds", "Показывать активные бинды" },
				{ "Always On Binds", "Показывать постоянные" },
				{ "Hold Binds", "Показывать удерживаемые" },
				{ "Toggle Binds", "Показывать переключаемые" },
				{ "BOMB PANEL", "ПАНЕЛЬ БОМБЫ" },
				{ "Show Bomb Info", "Показывать информацию о бомбе" },
				{ "No active entries", "Нет активных записей" },
				{ "Spectators", "Наблюдатели" },

				{ "Steam Avatars", "Аватары Steam" },
				{ "  fixed camera", "  фикс. камера" },
				{ "  first person", "  от первого лица" },
				{ "  third person", "  от третьего лица" },
				{ "  free camera", "  свободная камера" },

				{ "CFG FILE", "КОНФИГ" },
				{ "File Name", "Имя файла" },
				{ "Export Named CFG", "Сохранить" },
				{ "Save As...", "Сохранить как..." },
				{ "Open CFG", "Загрузить" },
				{ "Browse...", "Обзор..." },

				{ "ESP EDITOR", "РЕДАКТОР ESP" },
				{ "PREVIEW UNAVAILABLE", "ПРЕДПРОСМОТР НЕДОСТУПЕН" },

				{ "Manual lineup", "Ручная раскидка" },
				{ "Hold {}, release", "Зажать {}, отпустить" },
				{ "Hold {}, {}, release", "Зажать {}, {}, отпустить" },
				{ "LMB", "ЛКМ" },
				{ "RMB", "ПКМ" },
				{ "LMB+RMB", "ЛКМ+ПКМ" },
				{ "m", "м" },

				{ "Jump+Throw", "Джамп троу" },
				{ "W+Jump+Throw", "W+Джамп троу" },
				{ "Run+Jump+Throw", "Бег+Джамп троу" },
				{ "Walk+Jump+Throw", "Шаг+Джамп троу" },
				{ "Crouch+Jump+Throw", "Присед+Джамп троу" },
				{ "Crouch+W+Jump+Throw", "Присед+W+Джамп троу" },
				{ "Crouch+Run+Jump+Throw", "Присед+Бег+Джамп троу" },
				{ "WJump+Throw", "W+Джамп троу" },
				{ "Jump+Throw LRMB", "Джамп троу ЛКМ+ПКМ" },
				{ "Jump+Throw RMB", "Джамп троу ПКМ" },
				{ "W+Jump+Throw LRMB", "W+Джамп троу ЛКМ+ПКМ" },
				{ "W+Jump+Throw RMB", "W+Джамп троу ПКМ" },
				{ "Run+Jump+Trhow", "Бег+Джамп троу" },
				{ "W+Jump+Throwv", "W+Джамп троу" },
				{ "Throw", "Бросок" },
				{ "Throw LRMB", "Бросок ЛКМ+ПКМ" },
				{ "Throw RMB", "Бросок ПКМ" },
				{ "Throw (crouch)", "Бросок в приседе" },
				{ "Throw (break glass)", "Бросок (разбить стекло)" },
				{ "Run+Thorw", "Бросок в беге" },
				{ "Run+Throw", "Бросок в беге" },
				{ "Crouch+Run+Throw", "Присед+Бросок в беге" },
				{ "Go Left then W+Jump+Throw", "Влево, затем W+Джамп троу" },
				{ "Go Right then W+Jump+Throw", "Вправо, затем W+Джамп троу" },
				{ "Complex, move left and back and jumpthrow while running", "Сложная: влево-назад, джамп троу в беге" },
				{ "Insta Window (no autothrow)", "Insta Window (без автоброска)" },
				{ "Insta Long Door (no autothrow)", "Insta Long Door (без автоброска)" },

				{ "Jump", "Прыжок" },
				{ "Crouch", "Присед" },
				{ "Run", "Бег" },
				{ "Walk", "Шаг" },
				{ "Step", "Шаг" },
				{ "Forward", "Вперёд" },

				{ "Trhow", "Бросок" },
				{ "Thorw", "Бросок" },
				{ "Throwv", "Бросок" },
			};

			return table;
		}

	}

	void set( id value )
	{
		if ( value >= id::en && value < id::count )
		{
			g_current.store( value, std::memory_order_relaxed );
		}
	}

	id current( )
	{
		return g_current.load( std::memory_order_relaxed );
	}

	const char* code( id value )
	{
		return value == id::ru ? "RU" : "EN";
	}

	const char* tr( const char* english )
	{
		if ( !english || current( ) == id::en )
		{
			return english;
		}

		const auto& table = russian( );
		const auto it = table.find( std::string_view{ english } );
		return it == table.end( ) ? english : it->second;
	}

	std::string_view tr( std::string_view english )
	{
		if ( current( ) == id::en )
		{
			return english;
		}

		const auto& table = russian( );
		const auto it = table.find( english );
		return it == table.end( ) ? english : std::string_view{ it->second };
	}

}
